modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/anviaan/MoreBeeInfo/issues"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="https://anvian-page.netlify.app/forge/bee_info.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/morebeeinfo"
logoFile="assets/bee_info/icon.png"
authors="${mod_authors}"
description='''${mod_description}'''
displayTest="IGNORE_ALL_VERSION"

[[dependencies.${mod_id}]]
   modId="forge"
   mandatory=true
   versionRange="${forge_version_range}"
   ordering="NONE"
   side="CLIENT"
[[dependencies.${mod_id}]]
   modId="minecraft"
   mandatory=true
   versionRange="${minecraft_version_range}"
   ordering="NONE"
   side="BOTH"
